from collections import namedtuple
import configparser
import os
import sys
import argparse
import numpy as np

# Above can be avoided by pip install --editable .

from gref4hsi.utils import parsing_utils, uhi_parsing_utils
from gref4hsi.scripts import georeference, orthorectification
from gref4hsi.utils import visualize
from gref4hsi.utils.config_utils import (
    prepend_data_dir_to_relative_paths,
    customize_config,
)


def main(args):
    # DATA_DIR = os.path.join(base_fp, "HyperspectralDataAll/UHI/2020-07-01-14-40-15-ArcticSeaIce-Ben-Lange/")

    # DATA_DIR is a string that points to the directory where the data is stored
    DATA_DIR = args.data_dir

    # The configuration file stores the settings for georeferencing. This line is just a declaration ie its empty
    # if the file exists however, the "config_file_mission" will just be the path to the file
    config_file_mission = os.path.join(DATA_DIR, "configuration.ini")

    config_path_template = os.path.join(
        DATA_DIR, "configuration_uhi.ini"
    )  # os.path.join(home, 'VsCodeProjects/gref4hsi/data/config_examples/configuration_uhi.ini')

    """
    This line above creates a path to a template configuration file called configuration_uhi.ini. You need two config files because they serve different purposes:

    Why Two Config Files?
    configuration_uhi.ini (Template):

    This is a template/example configuration file
    Contains default settings and examples for UHI processing
    Acts as a starting point with all the necessary sections and parameters
    Located in your data directory (or could be in the examples folder as shown in the comment)
    configuration.ini (Mission-specific):

    This is the actual working configuration file for your specific mission/dataset
    Gets created by copying and modifying the template
    Contains the final settings that will be used for processing your specific data
    The Workflow:
    Start with template: configuration_uhi.ini has all the default UHI settings
    Copy to mission config: The template gets copied/processed to create configuration.ini
    Customize for your data: The customize_config() function then modifies configuration.ini with your specific command-line arguments (resolution, interpolation method, etc.)
    Use for processing: All the processing functions (georeference.main(), orthorectification.main(), etc.) read from the final configuration.ini
    This approach allows you to:

    Keep a clean template with all default settings
    Create mission-specific configurations without modifying the original template
    Easily customize settings via command-line arguments
    Maintain consistency across different processing runs
    It's essentially a "template → customize → use" pattern that's common in data processing pipelines.

    Required Files (Must Exist Before Running):
    configuration_uhi.ini - The template configuration file
    Location: DATA_DIR/configuration_uhi.ini
    This is the template that contains all the default UHI processing settings
    You must create/copy this file to your data directory before running the script

    Files That Get Created Automatically:
    configuration.ini - The mission-specific config file
    Location: DATA_DIR/configuration.ini
    This gets created automatically by copying and modifying configuration_uhi.ini
    You DON'T need to create this - it's generated by the script

    """

    # Copies the template "configuration_uhi.ini" to "config_file_mission" and sets up the necessary directories
    prepend_data_dir_to_relative_paths(
        config_path=config_path_template, DATA_DIR=DATA_DIR
    )

    """
    This function call does two main things:

    1. Copies the Template Configuration
    Takes the template config file (configuration_uhi.ini)
    Copies it to create the mission-specific config file (configuration.ini)
    This gives you a working copy of the configuration that you can modify without touching the original template
    2. Converts Relative Paths to Absolute Paths
    The template configuration file likely contains relative file paths like:

    [Absolute Paths]
    hyperspectral_dir = Input/Hyperspectral/
    nav_dir = Input/Navigation/
    dem_path = Input/GIS/dummy_dem.tif
    model_path = Input/GIS/model.ply

    The function prepends your DATA_DIR to these relative paths, converting them to absolute paths:

    [Absolute Paths]
    hyperspectral_dir = E:/mjosa/Svea2_Day_1/Gref_Transect_2/Gref_10mm_DVL_minimal_inter/Input/Hyperspectral/
    nav_dir = E:/mjosa/Svea2_Day_1/Gref_Transect_2/Gref_10mm_DVL_minimal_inter/Input/Navigation/
    dem_path = E:/mjosa/Svea2_Day_1/Gref_Transect_2/Gref_10mm_DVL_minimal_inter/Input/GIS/dummy_dem.tif
    model_path = E:/mjosa/Svea2_Day_1/Gref_Transect_2/Gref_10mm_DVL_minimal_inter/Input/GIS/model.ply

    3. Creates Necessary Directories
    The function also creates any directories that don't exist yet (like Input/Hyperspectral/, Input/Navigation/, etc.) within your data directory.

    Why This is Important:
    Portability: The template can use relative paths, making it work on any system
    Organization: All file paths are automatically organized under your specific data directory
    Automation: You don't have to manually edit configuration files or create directory structures
    Safety: The original template remains unchanged
    This is essentially setting up your data directory structure and creating a personalized configuration file that points to the correct locations for your specific UHI dataset.
    """

    # The custom_config dictionary is taking the command-line arguments you passed in experiment_run.sh and plugging them into specific configuration settings. It's essentially implementing/applying your custom settings to override the defaults.
    # TODO: check if this is correct

    custom_config = {
        "Orthorectification": {
            "resample_rgb_only": False,  # Good choice for speed
            "resample_ancillary": False,
            "resolutionhyperspectralmosaic": args.resolution,  # 1cmm
            "raster_transform_method": args.raster_transform,
            "mask_pixel_by_footprint": args.interpolation,
        },
        "HDF.raw_nav": {
            "file_type": args.alti_data
        },  # what file to use for altimeter data
        "HDF.hyperspectral": {"is_calibrated": False},
        # the geoid is the whole globe so its not mission/campaign specific, thus the egm08_25.gtx just have to be given
        "Absolute Paths": {
            "geoid_path": os.path.join(
                r"C:\Users\Erik Liu\OneDrive - NTNU\PhD\Courses\UHI post processing\havard_repo\from_Leo_usb\gref4hsi\data\world\geoids\egm08_25.gtx"
            )
        },
        "Coordinate Reference Systems": {
            "proj_epsg": 32633,
            "dem_epsg": 32633,
        },  # TODO: i used different for EIVA
    }

    # Customizes the config file with the dict. defined above
    customize_config(config_path=config_file_mission, dict_custom=custom_config)
    """
    The line customize_config(config_path=config_file_mission, dict_custom=custom_config) applies your custom settings to the configuration file. Here's exactly what it does:

    What This Function Does:
    Reads the existing config file (configuration.ini) that was created earlier
    Overwrites specific settings with your custom values from the custom_config dictionary
    Saves the updated config back to the file
    """

    # Settings specific to the pre-processing of UHI data. At present they are hardcoded, but they could be integrated
    # namedtuple is bascialy just a fixed simple dict that is more lightweight than a normal dict. its created to just have better overview and its filled in right after in the next code
    SettingsPreprocess = namedtuple(
        "SettingsPreprocessing",
        [
            "dtype_datacube",
            "rotation_matrix_hsi_to_body",
            "translation_body_to_hsi",
            "rotation_matrix_alt_to_body",
            "translation_alt_to_body",
            "config_file_name",
            "time_offset_sec",
            "lon_lat_alt_origin",
            "resolution_dem",
            "agisoft_process",
        ],
    )

    # regarding timesync:
    """
    Great question! Let's work through this example to clarify the time offset convention.

    Given:

    UHI timestamp: 1005
    IMU timestamp: 1000
    These represent the same physical moment
    The Time Offset Calculation:
    The time offset represents: UHI time - IMU time
    time_offset = UHI_time - IMU_time = 1005 - 1000 = +5
    So time_offset = +5 (UHI is 5 seconds ahead of IMU).

    How This Gets Used:
    To convert UHI time → IMU time (for processing):

    true_time_hsi = hyp.hsi_frames_timestamp - time_offset
    true_time_hsi = 1005 - 5 = 1000  # Now in IMU time frame

    To convert IMU time → UHI time (for H5 storage):

    hsi_synced_nav_timestamp_rov = nav_timestamp_rov + time_offset
    hsi_synced_nav_timestamp_rov = 1000 + 5 = 1005  # Now in UHI time frame

    Verification:
    After both conversions, the timestamps align:

    UHI data in IMU time: 1000
    Nav data in UHI time: 1005
    Both represent the same moment, just in different time references
    Answer: The time offset should be +5

    This means UHI clock is running 5 seconds ahead of the IMU clock. The positive offset correctly captures this relationship and allows the code to synchronize between the two time domains.

    """
    # TODO: check if this is correct
    config_uhi_preprocess = SettingsPreprocess(
        #  Data type for hyperspectral cube
        dtype_datacube=np.float32,
        rotation_matrix_hsi_to_body=np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]]),
        # Translation t so that vec_body_to_object = vec_hsi_to_object + t
        translation_body_to_hsi=np.array([0, 0, 0]),
        # TODO: wtf is this -> check up where its used
        rotation_matrix_alt_to_body=np.array([[0, 1, 0], [-1, 0, 0], [0, 0, 1]]),
        # Boolean being expressing whether to rectify only composite (true) or data cube and composite (false). True is fast.
        translation_alt_to_body=np.array([0, 0, 0]),
        # TODO: idk if this make sense as this code is ran for one transect at the time so wtf is this offset -> edit: looks like this is the time offset between the altimeter and the hyperspectral camera(?), edit: time sync between UHI and IMU:
        # ie: true_time_hsi = hyp.hsi_frames_timestamp - time_offset
        #
        # Ben's tick s1 starts at 1593614097.992003 -> 22 s delay
        # Ben's tick s2 starts at 1593614414.995001 -> 0 s delay
        time_offset_sec=args.time_offset_sec,
        lon_lat_alt_origin=np.array([15.780755, 77.782882, 0]),  # SVEA#
        config_file_name="configuration.ini",
        resolution_dem=0.2,  # The resolution of the Altimeter-based DEM
        # This is an option for photogrammetry-based processing in the case you have imagery
        agisoft_process=False,
    )

    # Add camera offset configuration to the config file
    # camera_config = {
    #     "Camera": {
    #         "translation_body_to_hsi_x": config_uhi_preprocess.translation_body_to_hsi[
    #             0
    #         ],
    #         "translation_body_to_hsi_y": config_uhi_preprocess.translation_body_to_hsi[
    #             1
    #         ],
    #         "translation_body_to_hsi_z": config_uhi_preprocess.translation_body_to_hsi[
    #             2
    #         ],
    #     }
    # }
    # customize_config(config_path=config_file_mission, dict_custom=camera_config)

    # The config stores all relevant configurations -> basically just like a empty box
    # creates a fresh configparser -> this is like an empty container
    config = configparser.ConfigParser()
    config.read(config_file_mission)  # fils the empty box with the config.ini file

    # The minimum for georeferencing is to parse 1) Mesh model and 2) The pose of the reference
    """
    # basiclly just updates .h5 file with pose data and also a DEM from the altitude sensor. its saved at dem_path = E:\mjosa\Svea2_Day_1\Gref_Transect_2\Gref_10mm_DVL_minimal_inter\Input/GIS/dummy_dem.tif
    # this function could prove useful when i do stuff myself and see that stuff is not working correctly -> see that theres some heavly code at times 
    # if theres something wrong with my code, can see each function used in this uhi_dbe -> i just skimmed the function for what it produced and did. didnt go into details 
    """
    uhi_parsing_utils.uhi_dbe(config=config, config_uhi=config_uhi_preprocess)

    """
    === UHI data preparation overview ===

    There are two steps in preparing navigation and pose data:

    Step 1: "uhi_dbe"
    ---------------
    - Reads raw navigation data from sensors (IMU, DVL, Altimeter).
    - Synchronizes raw nav data roughly with the hyperspectral timestamps.
    - Writes robot-centered position and orientation into the h5 files.
    - Navigation is still basic: in NED or local coordinates, and not fully aligned with images.
    - Used mainly to inject some initial pose information for later steps.
    - Altimeter data is also converted into a point cloud and a simple DEM.

    Important:
    - This step does NOT yet produce the final poses that match every hyperspectral image exactly. it just adds basic navigation data to the .h5 files. none of the datacube has been even used (only timestamp from UHI and spatial pixels to find spatial binning)
    - It only adds raw, interpolated robot nav into the h5 files.

    Step 2: "export_pose"
    ---------------------
    - Reads the rough nav data injected in the h5 files.
    - Interpolates navigation precisely to each hyperspectral frame.
    - Converts rotation into global ECEF format.
    - Adjusts pose if needed (e.g., for sensor offset if camera is not at robot center).
    - Saves final, synchronized, global pose (position + orientation) into the h5 files under /Nav.
    - These final poses are ready for orthorectification, DEM building, and 3D modeling.

    Summary:
    ---------
    - "uhi_dbe" → prepares basic navigation and rough altitude DEM.
    - "export_pose" → generates final, corrected camera poses ready for mapping and model generation.

    Always run both steps when preparing UHI data for georeferenced mapping.
    """

    #  this function bascilly transforms data from IMU to coordainte system of camera and gives new poses
    # ie the new poses found in the master csv is in camera frame
    config = parsing_utils.export_pose(config_file_mission)

    config = configparser.ConfigParser()

    config.read(config_file_mission)

    # Exports model
    """
    export the DEm model from before made by the altiude sensor. now it take in from the config file what type of model 
    shall be exported, like shall it be a format to be used by agisoft for photgrammatry, or maybe a mesh maade by triangles instead of
    just a DEM where its a grid with a value (this is discrete values, its not conitinous)
    
    chatgpt:
    From uhi_dbe:

    You had altitude measurements from DVL/altimeter.

    Those were used to build a DEM file (Digital Elevation Model).

    DEM = A 2D grid where each cell holds a height (Z value).

    Now (export_model step):

    You take that DEM (height map).

    You convert it into a 3D surface mesh (by connecting neighboring points into little triangles).

    You save that surface as a .ply file.

    Result:

    Now you have a 3D model that you can open in Blender, MeshLab, or CloudCompare.

    It looks like the terrain/sea bottom scanned by your drone!
    """

    # creates a 3D surface mesh (small triangles) from the DEM
    # this is the 3D model that will be used in georeferencing
    parsing_utils.export_model(config_file_mission)

    # Visualize the data 3D photo model from RGB images and the time-resolved positions/orientations
    # visualize.show_mesh_camera(config, ref_frame = 'ENU')

    """
    Explanation of how the 3D model used in georeferencing is created and loaded:

    Step 1: What model does georeference.main() load?
    - It reads `model_path` from the config under [Absolute Paths]. -> ie the 3D model created by export_model()
    - Example: model_path = E:/.../Input/GIS/model.ply
    - So it loads the 3D model `model.ply`.

    Step 2: Where does model.ply come from?
    - Before georeferencing, the script calls parsing_utils.export_model(config_file_mission).
    - Inside export_model():
        - It checks model_export_type = dem_file.
        - It reads the DEM file from dem_path = E:/.../Input/GIS/dummy_dem.tif.
        - It calls dem_2_mesh() to convert the DEM into the 3D model (model.ply).

    Step 3: What DEM is used?
    - The DEM used is dummy_dem.tif.
    - This file was created during uhi_dbe() from the altimeter data.
    - uhi_dbe() makes a point cloud → converts it into a DEM → saves it as dummy_dem.tif.

    Step 4: Full Chain:
    - uhi_dbe(): Creates dummy_dem.tif from altimeter point cloud.
    - export_model(): Converts dummy_dem.tif into model.ply (3D mesh).
    - georeference.main(): Loads model.ply and uses it to intersect HSI rays.

    Visual summary:
    [Altitude measurements] → [Point Cloud] → [DEM: dummy_dem.tif] → [3D Model: model.ply] → [Used in Georeferencing]

    Conclusion:
    The 3D model used in georeferencing is model.ply, which was generated from dummy_dem.tif, which was created based on the altitude data during uhi_dbe.
    """

    # Georeference the line scans of the hyperspectral imager. Utilizes parsed data

    """
    georef.main does not return anything.
    It saves everything directly into the H5 file you loaded.

    Step-by-step:

    1. Reads the hyperspectral H5 file.

    2. Adds new datasets inside that same H5 file:
    - Intersection points
    - Normals
    - View angles
    - Sun angles
    - Tide corrections
    - Seabed depth

    3. Updates the H5 file on disk.
    """
    georeference.main(config_file_mission)

    # todo start from here 26.04.2025
    orthorectification.main(config_file_mission)
    """
    looks like this feature was removed
    """
    # Alternatively mode = 'calibrate'
    # georeference.main(config_file, mode='calibrate', is_calibrated=True)


if __name__ == "__main__":

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--data_dir",
        type=str,
        default="C:/Users/Erik Liu/OneDrive - NTNU/PhD/Courses/UHI post processing/havard_repo/from_Leo_usb/Svea3_Day1/Gref_Transect_2a/Gref_10mm_DVL_minimal_inter/",
        # default above use this path only if a data_dir is not given before
    )
    parser.add_argument("--resolution", type=float, default=0.01)
    parser.add_argument("--interpolation", type=bool, default=True)
    parser.add_argument("--alti_data", type=str, default="dvl")
    parser.add_argument("--raster_transform", type=str, default="north_east")
    parser.add_argument("--time_offset_sec", type=int, default=0)
    args = parser.parse_args()
    # print("ewfghuwehufiewfhwe")
    main(args)
